remote_theme: pages-themes/time-machine@v0.2.0

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-github-metadata

title: Taller de IA
description: Taller de IA para mis amigas :)

baseurl: "/taller"